site_name: BDD for command-line applications
theme: readthedocs
markdown_extensions:
    - markdown_include.include
    - admonition
    - toc:
        anchorlink: True
pages:
- Home: index.md
- Behave: behave.md
- Lettuce: lettuce.md
- Steps: 
    - steps/environment.md
    - steps/file.md
    - steps/command.md
- Development: development.md
